apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dsav-mongo
  labels:
    db: dsav-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        db: dsav-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        volumeMounts:
        - mountPath: /data/db
          name: mongo-vol
      restartPolicy: Always
      volumes:
      - name: mongo-vol
        hostPath:
          path: /data/digital_saving_vol_mongo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: dsav-mongo
spec:
  selector:
    db: dsav-mongo
  type: NodePort
  ports:
    - port: 27017
      nodePort: 31111