apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tnindo-postgres
  labels:
    db: tnindo-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        db: tnindo-postgres
    spec:
      containers:
      - name: tnindo-postgres
        image: tnindo/postgresql:v2
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-vol
      restartPolicy: Always
      volumes:
      - name: postgres-vol
        hostPath:
          path: /data/saving_postgres/
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: tnindo-postgres
  labels: 
    db: tnindo-postgres
spec:
  ports:
  -  port: 5432
     targetPort: 5432
     nodePort: 31008
  type: LoadBalancer
  selector:
    db: tnindo-postgres