apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dsav-redis
  labels:
    run: dsav-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: dsav-redis
    spec:
      containers:
      - name: redis
        image: redis
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: dsav-redis
spec:
  type: NodePort
  selector:
    run: dsav-redis
  ports:
    - name: dsav-redisport
      port: 6379
      nodePort: 31112
