apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    db: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
      - name: postgres
        image: tnindo/postgresql:v2
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-vol
      restartPolicy: Always
      volumes:
      - name: postgres-vol
        hostPath:
          path: /data/saving_postgres/
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    run: postgres
spec:
  ports:
  -  port: 5432
     targetPort: 5432
     nodePort: 31008
     name: tcp
     protocol: TCP
  type: NodePort
  selector:
    db: postgres