# this file for deployment report
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: report
  labels:
    app: report
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: report
    spec:
      # affinity:     
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: app
      #             operator: In
      #             values: ["yes"]
      containers:
      - name: report
        image: tnindo/report:v1stag.0.16
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /go/src/report/logs
          name: report-logs
        env:
        - name: GOPATH
          value: "/go"
        - name: GOAPP
          value: "report"
        - name: GOENV
          value: "kube"
        - name: SMITHBANKID
          value: "009"
        - name: HTTP
          value: "kube"
        - name: RPC
          value: "kube"
        # - name: CRED_MONGODB
          # value: "mongodb://mongo:27017"
#        - name: CRED_MQ
#          value: "amqp://savrabbit:savrabbit@savrabbitmq:5672/"
        - name: CRED_PGSQL
          value: "postgres://postgres:root@172.17.0.1:31008/smith_report?sslmode=disable"
        - name: CRED_SQLITE
          value: ":memory:"
        - name: RPC_TXN
          value: "txn@172.17.0.1:32104"
      restartPolicy: Always
      volumes:
      - name: report-logs
        hostPath:
          path: /data/saving_vol_report/logs
      imagePullSecrets:
      - name: regsecret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: report
  labels:
    app: report
spec:
  ports:
  -  port: 8086
     targetPort: 8086
     nodePort: 30006
     name: app
  - port: 58086
    targetPort: 58086
    nodePort: 32106
    name: grpc
  type: LoadBalancer
  selector:
    app: report
