# this file for deployment rulestxn
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rulestxn
  labels:
    app: rulestxn
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rulestxn
    spec:
      containers:
      - name: rulestxn
        image: tnindo/rulestxn:v1stag.0.34
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /go/src/general-transaction-rule/logs
          name: rules-logs
        env:
        - name: GOPATH
          value: "/go"
        - name: GOENV
          value: "kube"
        - name: GOAPP
          value: "general-transaction-rule"
        - name: SMITHBANKCODE
          value: "009"
        - name: HTTP
          value: "kube"
        - name: RPC
          value: "kube"
        - name: OLDCBSURL
          value: "/incoming/validate/OLDCBS"
        - name: OTHBANKURL
          value: "/incoming/validate/OTHBANK"
        - name: OUTGOINGURL
          value: "/outgoing/validate/OnlineTransfer"
        - name: CRED_MONGODB
          value: "mongodb://172.17.0.1:31111"
#        - name: CRED_MQ
#          value: "amqp://savrabbit:savrabbit@savrabbitmq:5672/"
        - name: CRED_REDIS
          value: "172.17.0.1:31112"
        - name: SMITHEARNINGREDEMPTIONBANKCODE
          value: "030"
      restartPolicy: Always
      volumes:
      - name: rules-logs
        hostPath:
          path: /data/saving_vol_rulestxn/logs
      imagePullSecrets:
      - name: regsecret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: rulestxn
  labels:
    app: rulestxn
spec:
  ports:
  -  port: 8083
     targetPort: 8083
     nodePort: 30003
     name: app
  -  port: 18083
     targetPort: 18083
     nodePort: 30103
     name: socket
  - port: 58083
    targetPort: 58083
    nodePort: 32103
    name: grpc
  type: LoadBalancer
  selector:
    app: rulestxn
