--
-- Name: 
--    reports_04_report_registry.sql
-- Purpose: 
--  Defines report definitions that are available to the API
--
-- \c core_reports specifies to which database to use in pgsql
\c core_reports
BEGIN;

--
-- Data for Name: reports; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.reports VALUES ('1', 'bal_2', 'Position Balance By Product', 'fr_run_bal_2');
INSERT INTO public.reports VALUES ('9', 'sav_10', 'Transaction Exceptions', 'fr_run_sav_10');
INSERT INTO public.reports VALUES ('12', 'sav_10a', 'Transaction Details', 'fr_run_sav_10a');
INSERT INTO public.reports VALUES ('10', 'sav_11', 'Savings Account Balance by Product', 'fr_run_sav_11');
INSERT INTO public.reports VALUES ('2', 'bal_2a', 'General Ledger Account Balance Report', 'fr_run_bal_2a');
INSERT INTO public.reports VALUES ('11', 'trns_4', 'Manually Posted Transactions', 'fr_run_trns_4');
INSERT INTO public.reports VALUES ('4', 'bal_6', 'General Ledger Account Transactions by Process Date', 'fr_run_bal_6');
INSERT INTO public.reports VALUES ('3', 'bal_5', 'All Transactions For Calendar Day/Accounting Day', 'fr_run_bal_5');
INSERT INTO public.reports VALUES ('6', 'dep_5', 'Orders by Processing Date, Network and Status', 'fr_run_dep_5');
INSERT INTO public.reports VALUES ('5', 'dep_4', 'Posted Interest - All Positions', 'fr_run_dep_4');
INSERT INTO public.reports VALUES ('8', 'sav_6', 'New Savings Accounts by Opening Date and Product', 'fr_run_sav_6');
INSERT INTO public.reports VALUES ('7', 'sav_2', 'Bank Accounts Possibly in Violation of Reg D', 'fr_run_sav_2');
INSERT INTO public.reports VALUES ('13', 'gl_bal', 'GL Balancing Report', 'fr_run_gl_bal');
--
-- Data for Name: report_input; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.report_input VALUES ('1', 'procdate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('2', 'procdate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('3', 'procdate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('4', 'procdate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('5', 'frprocdate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('5', 'toprocdate', 2, 'timestamp', true);
INSERT INTO public.report_input VALUES ('6', 'frprocdate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('6', 'toprocdate', 2, 'timestamp', true);
INSERT INTO public.report_input VALUES ('7', 'frprocdate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('7', 'toprocdate', 2, 'timestamp', true);
INSERT INTO public.report_input VALUES ('8', 'fropendate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('8', 'toopendate', 2, 'timestamp', true);
INSERT INTO public.report_input VALUES ('8', 'procdate', 3, 'timestamp', true);
INSERT INTO public.report_input VALUES ('9', 'procdate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('10', 'procdate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('11', 'procdate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('12', 'procdate', 1, 'timestamp', true);
INSERT INTO public.report_input VALUES ('13', 'procdate', 1, 'timestamp', true);


--
-- Data for Name: report_section; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.report_section VALUES ('5', 'dep_4_dtl', 0, NULL, 'detail', NULL, '[{"align": "R", "width": 18, "columnName": "Data As Of"}, {"align": "R", "width": 28, "columnName": "Position"}, {"align": "L", "width": 25, "columnName": "Prod"}, {"align": "L", "width": 18, "columnName": "Prod Type"}, {"align": "L", "width": 30, "columnName": "GL Set"}, {"align": "L", "width": 8, "columnName": "Ccy"}, {"align": "L", "width": 24, "columnName": "Tran Code"}, {"align": "L", "width": 18, "columnName": "Effective"}, {"align": "L", "width": 18, "columnName": "GL Jrnl Dt"}, {"align": "L", "width": 22, "columnName": "Lst Post Dt"}, {"align": "L", "width": 22, "columnName": "Nxt Post Dt"}, {"align": "R", "width": 18, "columnName": "Int Rate"}, {"align": "L", "width": 25, "columnName": "Index"}, {"align": "L", "width": 20, "columnName": "Review Freq"}, {"align": "L", "width": 22, "columnName": "Nxt Rate Chng"}, {"align": "R", "width": 18, "columnName": "Stmt APYE"}, {"align": "L", "width": 22, "columnName": "Promo Rt Exp"}, {"align": "L", "width": 40, "columnName": "Tfr Int to Acct"}, {"align": "L", "width": 40, "columnName": "Tfr Int to Acct Title"}, {"align": "L", "width": 40, "columnName": "Tfr Int to Acct Inst"}, {"align": "L", "width": 25, "columnName": "Network"}, {"align": "L", "width": 40, "columnName": "BatchID"}, {"align": "L", "width": 40, "columnName": "Tran Id"}, {"align": "L", "width": 40, "columnName": "Reverse"}, {"align": "L", "width": 40, "columnName": "Reversed By"}, {"align": "L", "width": 10, "columnName": "Mode"}, {"align": "L", "width": 40, "columnName": "Log Ref"}, {"align": "R", "width": 28, "columnName": "Dr Amount"}, {"align": "R", "width": 28, "columnName": "Cr Amount"}]');
INSERT INTO public.report_section VALUES ('6', 'dep_5_dtl', 0, NULL, 'detail', NULL, '[{"width":18,"align":"R","columnName":"Data As Of"},{"width":28,"align":"R","columnName":"Position"},{"width":50,"align":"L","columnName":"Title"},{"width":25,"align":"L","columnName":"Network"},{"width":20,"align":"L","columnName":"Order Type"},{"width":24,"align":"L","columnName":"Order Source"},{"width":18,"align":"L","columnName":"Order Date"},{"width":20,"align":"L","columnName":"Verify Date"},{"width":50,"align":"L","columnName":"Check By"},{"width":40,"align":"L","columnName":"Origin Source"},{"width":50,"align":"L","columnName":"Originate By"},{"width":20,"align":"L","columnName":"Create Date"},{"width":50,"align":"L","columnName":"Create By"},{"width":50,"align":"L","columnName":"Counterparty Title"},{"width":50,"align":"L","columnName":"Counterparty AccNbr"},{"width":22,"align":"R","columnName":"Order Status"},{"width":18,"align":"L","columnName":"Frequency"},{"width":22,"align":"L","columnName":"Expire Date"},{"width":18,"align":"L","columnName":"Last Date"},{"width":18,"align":"L","columnName":"Next Date"},{"width":12,"align":"R","columnName":"Count"},{"width":16,"align":"R","columnName":"Remaining"},{"width":28,"align":"R","columnName":"Order Amount"},{"width":32,"align":"R","columnName":"Threshhold Amount"},{"width":32,"align":"R","columnName":"Available Balance"},{"width":28,"align":"R","columnName":"Balance"}]');
INSERT INTO public.report_section VALUES ('9', 'sav_10_dtl', 0, NULL, 'detail', NULL, '[{"align": "L", "width": 60, "columnName": "Tran ID"}, {"align": "R", "width": 18, "columnName": "Data As Of"}, {"align": "R", "width": 28, "columnName": "Account"}, {"align": "R", "width": 28, "columnName": "Position"}, {"align": "L", "width": 20, "columnName": "Prod"}, {"align": "L", "width": 8, "columnName": "Ccy"}, {"align": "L", "width": 28, "columnName": "Tran Code"}, {"align": "R", "width": 18, "columnName": "Effective"}, {"align": "R", "width": 18, "columnName": "GL Jrnl Dt"}, {"align": "L", "width": 60, "columnName": "Reverse"}, {"align": "L", "width": 60, "columnName": "Reversed By"}, {"align": "R", "width": 35, "columnName": "Dr Amount"}, {"align": "R", "width": 35, "columnName": "Cr Amount"}, {"align": "L", "width": 12, "columnName": "Auth All"}, {"align": "L", "width": 40, "columnName": "ExCode"}, {"align": "L", "width": 40, "columnName": "Reason"}, {"align": "L", "width": 60, "columnName": "Log Ref"}, {"align": "L", "width": 40, "columnName": "Note"}, {"align": "L", "width": 25, "columnName": "Network"}, {"align": "L", "width": 30, "columnName": "Mode"}, {"align": "L", "width": 20, "columnName": "BatchID"}]');
INSERT INTO public.report_section VALUES ('2', 'bal_2a_dtls', 0, NULL, 'detail', NULL, '[{"width":18,"align":"R","columnName":"Data As Of"},{"width":12,"align":"L","columnName":"Cat"},{"width":30,"align":"R","columnName":"Account"},{"width":80,"align":"L","columnName":"Name"},{"width":12,"align":"L","columnName":"Ccy"},{"width":30,"align":"R","columnName":"Balance"}]');
INSERT INTO public.report_section VALUES ('3', 'bal_5_dtl', 0, NULL, 'detail', NULL, '[{"align": "R", "width": 18, "columnName": "Data As Of"}, {"align": "R", "width": 28, "columnName": "Position"}, {"align": "L", "width": 20, "columnName": "Prod"}, {"align": "L", "width": 8, "columnName": "Ccy"}, {"align": "L", "width": 20, "columnName": "Tran Code"}, {"align": "R", "width": 18, "columnName": "Effective"}, {"align": "R", "width": 18, "columnName": "GL Jrnl Dt"}, {"align": "L", "width": 25, "columnName": "Network"}, {"align": "L", "width": 20, "columnName": "Batch ID"}, {"align": "L", "width": 40, "columnName": "Reverse"}, {"align": "L", "width": 40, "columnName": "Reversed By"}, {"align": "L", "width": 40, "columnName": "Mode"}, {"align": "L", "width": 40, "columnName": "Log Ref"}, {"align": "R", "width": 28, "columnName": "Dr Amount"}, {"align": "R", "width": 28, "columnName": "Cr Amount"}]');
INSERT INTO public.report_section VALUES ('4', 'bal_6_dtl', 0, NULL, 'detail', NULL, '[{"align": "R", "width": 28, "columnName": "Account"}, {"align": "R", "width": 28, "columnName": "Position"}, {"align": "L", "width": 8, "columnName": "Ccy"}, {"align": "L", "width": 20, "columnName": "Tran Code"}, {"align": "R", "width": 18, "columnName": "GL Jrnl Dt"}, {"align": "R", "width": 18, "columnName": "Effective"}, {"align": "R", "width": 28, "columnName": "Dr Amount"}, {"align": "R", "width": 28, "columnName": "Cr Amount"}, {"align": "L", "width": 40, "columnName": "Tran Id"}, {"align": "L", "width": 40, "columnName": "Reverse"}, {"align": "L", "width": 40, "columnName": "Reversed By"}, {"align": "L", "width": 25, "columnName": "Network"}, {"align": "L", "width": 40, "columnName": "Batch ID"}]');
INSERT INTO public.report_section VALUES ('7', 'sav_2_dtl', 0, NULL, 'detail', NULL, '[{"width":18,"align":"R","columnName":"Data As Of"},{"width":28,"align":"R","columnName":"Position"},{"width":50,"align":"L","columnName":"Title"},{"width":20,"align":"L","columnName":"Prod"},{"width":8,"align":"L","columnName":"Ccy"},{"width":40,"align":"L","columnName":"Tran Code"},{"width":50,"align":"L","columnName":"Description"},{"width":25,"align":"L","columnName":"Network"},{"width":40,"align":"L","columnName":"ID"},{"width":40,"align":"L","columnName":"Reverse"},{"width":40,"align":"L","columnName":"Reversed By"},{"width":28,"align":"R","columnName":"Amount"}]');
INSERT INTO public.report_section VALUES ('11','trns_4_dtl', 0, NULL, 'detail', NULL, '[{"align": "R", "width": 18, "columnName": "Data As Of"}, {"align": "R", "width": 28, "columnName": "Position"}, {"align": "L", "width": 20, "columnName": "Prod"}, {"align": "L", "width": 8, "columnName": "Ccy"}, {"align": "L", "width": 20, "columnName": "Tran Code"}, {"align": "R", "width": 18, "columnName": "Effective"}, {"align": "R", "width": 18, "columnName": "GL Jrnl Dt"}, {"align": "L", "width": 25, "columnName": "Network"}, {"align": "L", "width": 40, "columnName": "BatchID"}, {"align": "L", "width": 40, "columnName": "Reverse"}, {"align": "L", "width": 40, "columnName": "Reversed By"}, {"align": "L", "width": 8, "columnName": "Mode"}, {"align": "L", "width": 40, "columnName": "Log Ref"}, {"align": "R", "width": 28, "columnName": "Dr Amount"}, {"align": "R", "width": 28, "columnName": "Cr Amount"}]');
INSERT INTO public.report_section VALUES ('1', 'bal_2_dtls', 0, NULL, 'detail', NULL, '[{"width":18,"align":"R","columnName":"Data As Of"},{"width":28,"align":"R","columnName":"Position"},{"width":50,"align":"L","columnName":"Title"},{"width":20,"align":"L","columnName":"Prod"},{"width":30,"align":"L","columnName":"GL Set"},{"width":14,"align":"L","columnName":"Dept"},{"width":14,"align":"L","columnName":"Vert"},{"width":8,"align":"L","columnName":"Ccy"},{"width":28,"align":"R","columnName":"Balance"},{"width":32,"align":"R","columnName":"Available Balance"},{"width":28,"align":"R","columnName":"GL Balance"}, {"width":18,"align":"R","columnName":"Opened"}, {"width":10,"align":"L","columnName":"Brkrd"},{"width":18,"align":"R","columnName":"Int Rate"},{"width":26,"align":"R","columnName":"Next Rate Chng"},{"width":18,"align":"R","columnName":"Stmt APYE"},{"width":28,"align":"R","columnName":"Accrued Int"},{"width":20,"align":"R","columnName":"Int Last Pd"},{"width":18,"align":"R","columnName":"Nxt Pd Dt"},{"width":28,"align":"R","columnName":"Int Paid YTD"},{"width":28,"align":"R","columnName":"Fed Withheld"},{"width":28,"align":"R","columnName":"State Withheld"},{"width":8,"align":"L","columnName":"Hold"},{"width":8,"align":"L","columnName":"Rest"},{"width":8,"align":"L","columnName":"Stop"}]');
INSERT INTO public.report_section VALUES ('10','sav_11_dtl', 0, NULL, 'detail', NULL, '[{"align": "R", "width": 18, "columnName": "Data As Of"}, {"align": "R", "width": 28, "columnName": "Position"}, {"align": "L", "width": 50, "columnName": "Title"}, {"align": "L", "width": 20, "columnName": "Prod"}, {"align": "L", "width": 30, "columnName": "GL Set"}, {"align": "L", "width": 14, "columnName": "Dept"}, {"align": "L", "width": 14, "columnName": "Vert"}, {"align": "L", "width": 8, "columnName": "Ccy"}, {"align": "R", "width": 28, "columnName": "Balance"}, {"align": "R", "width": 32, "columnName": "Available Balance"}, {"align": "R", "width": 28, "columnName": "GL Balance"}, {"width":18,"align":"R","columnName":"Opened"}, {"align": "L", "width": 10, "columnName": "Brkrd"}, {"align": "R", "width": 18, "columnName": "Int Rate"}, {"align": "R", "width": 18, "columnName": "Stmt APYE"}, {"align": "R", "width": 18, "columnName": "Nxt Pd Dt"}, {"align": "R", "width": 28, "columnName": "Accrued Int"}, {"align": "R", "width": 28, "columnName": "Int Paid"}, {"align": "R", "width": 28, "columnName": "Fed Withheld"}, {"align": "R", "width": 28, "columnName": "State Withheld"}, {"align": "L", "width": 8, "columnName": "Hold"}, {"align": "L", "width": 8, "columnName": "Rest"}, {"align": "L", "width": 8, "columnName": "Stop"}]');
INSERT INTO public.report_section VALUES ('8', 'sav_6_dtl', 0, NULL, 'detail', NULL, '[{"width":18,"align":"R","columnName":"Opened"},{"width":8,"align":"L","columnName":"Prod"},{"width":20,"align":"L","columnName":"Prod Type"},{"width":30,"align":"R","columnName":"GL Set"},{"width":14,"align":"R","columnName":"Dept"},{"width":14,"align":"L","columnName":"Vert"},{"width":28,"align":"R","columnName":"Account"},{"width":8,"align":"L","columnName":"Ccy"},{"width":50,"align":"L","columnName":"Title"},{"width":10,"align":"L","columnName":"Brkrd"},{"width":18,"align":"R","columnName":"Int Rate"},{"width":30,"align":"R","columnName":"Pledged Balance"},{"width":22,"align":"R","columnName":"Funding Exp"},{"width":32,"align":"R","columnName":"Available Balance"},{"width":28,"align":"R","columnName":"Balance"}]');
INSERT INTO public.report_section VALUES ('12', 'sav_10a_dtl', 0, NULL, 'detail', NULL, '[{"align": "R", "width": 18, "columnName": "Data As Of"}, {"align": "R", "width": 18, "columnName": "GL Jrnl Dt"}, {"align": "R", "width": 18, "columnName": "Effective"}, {"align": "L", "width": 40, "columnName": "Tran ID"}, {"align": "L", "width": 28, "columnName": "Tran Code"}, {"align": "R", "width": 28, "columnName": "Position"}, {"align": "R", "width": 28, "columnName": "Dr Amount"}, {"align": "R", "width": 28, "columnName": "Cr Amount"}, {"align": "L", "width": 8, "columnName": "Ccy"}, {"align": "L", "width": 40, "columnName": "Rev Tran Id"}, {"align": "L", "width": 40, "columnName": "Rev By Tran Id"}, {"align": "L", "width": 24, "columnName": "Prod"}, {"align": "L", "width": 30, "columnName": "GL Set"},{"align": "L", "width": 25, "columnName": "Network"}, {"align": "L", "width": 40, "columnName": "BatchID"},{"align": "L", "width": 40, "columnName": "Log Ref"}, {"align": "R", "width": 28, "columnName": "Ledger"}, {"align": "R", "width": 28, "columnName": "Acr Int"}, {"align": "R", "width": 28, "columnName": "Avail Int"}, {"align": "R", "width": 28, "columnName": "Neg Acr"}, {"align": "R", "width": 28, "columnName": "Acr Fee"}, {"align": "R", "width": 28, "columnName": "State With"}, {"align": "R", "width": 28, "columnName": "Fed With"}]');
INSERT INTO public.report_section VALUES ('13', 'gl_bal_dtl', 0, NULL, 'detail', NULL, '[{"align":"R","width":18,"columnName":"GL Date"},{"align":"R","width":18,"columnName":"Region ID"},{"align":"R","width":14,"columnName":"Dept ID"},{"align":"R","width":28,"columnName":"Acct Number"},{"align":"L","width":50,"columnName":"Acct Title"},{"align":"R","width":20,"columnName":"Gl Category"},{"align":"R","width":28,"columnName":"Balance"},{"align":"R","width":24,"columnName":"Total Cr Cnt"},{"align":"R","width":24,"columnName":"Total Dr Cnt"},{"align":"R","width":24,"columnName":"Total Cr Amt"},{"align":"R","width":28,"columnName":"Total Dr Amt"}]');



END;