#%RAML 1.0
version: v1
title: SAV_TXN
baseUri: localhost:8002/sav_txn/v1
/incoming/validate/OTHBANK:
    description: Validate Incoming Transaction from Other Bank
    post:
        headers:
            X-Gravitee-Api-Key:
            x-request-id:
            x-job-id:
            x-real-ip:
            x-caller-service:
            x-caller-domain:
            datetime:
            accept:
            accept-language:
            accept-encoding:
            Content-Type:
            x-device:
            x-application:
            x-channel:
            user-agent:
        body:
            application/json:
                example:    |
                    {
                        "rqBody":{
                            "source_bank_code":"506",
                            "beneficiary_bank_code":"009",
                            "source_account_number":"5000000001226",
                            "beneficiary_account_number":"50000000096",
                            "transaction_amount": 1000000,
                            "service_branch": 1
                        }
                    }
        responses: 
            200:
                body: 
                    application/json:
                        example:  |
                            {
                                "rsBody": {
                                    "beneficiary_account_number": "50000000096",
                                    "beneficiary_account_name": "John Smith",
                                    "transaction_amount": 1000000,
                                    "to_account_branch": 0
                                },
                                "error": []
                            }
/incoming/submit/OTHBANK:
    description: Submit Incoming Transaction from Other Bank
    post:
        headers:
            X-Gravitee-Api-Key:
            x-request-id:
            x-job-id:
            x-real-ip:
            x-caller-service:
            x-caller-domain:
            datetime:
            accept:
            accept-language:
            accept-encoding:
            Content-Type:
            x-device:
            x-application:
            x-channel:
            user-agent:
        body:
            application/json:
                example:    |
                    {
                        "rqBody":{
                            "source_bank_code":"506",
                            "beneficiary_bank_code":"009",
                            "source_account_number":"5000000001226",
                            "beneficiary_account_number":"50000000096",
                            "transaction_amount": 1000000,
                            "service_branch": 1
                        }
                    }
        responses: 
            200:
                body: 
                    application/json:
                        example:  |
                            {
                                "rsBody": {
                                    "beneficiary_account_number": "50000000096",
                                    "beneficiary_account_name": "John Smith",
                                    "transaction_amount": 1000000,
                                    "to_account_branch": 0
                                },
                                "error": []
                            }
/balance/accounts:
    description: Inquiry Account Balance
    get:
        queryParameters:
            :account_number: array
        headers:
            X-Gravitee-Api-Key:
            x-request-id:
            x-job-id:
            x-real-ip:
            x-caller-service:
            x-caller-domain:
            datetime:
            accept:
            accept-language:
            accept-encoding:
            Content-Type:
            x-device:
            x-application:
            x-channel:
            user-agent:
        responses: 
            200:
                body: 
                    application/json:
                        example:  |
                            {
                                "rsBody": {
                                    "accounts": [
                                        {
                                            "account_number": "50000000039",
                                            "ledger_balance": 0
                                        }
                                    ]
                                },
                                "error": []
                            }
/products:
    description: Create new product
    post:
        headers:
            X-Gravitee-Api-Key:
            x-request-id:
            x-job-id:
            x-real-ip:
            x-caller-service:
            x-caller-domain:
            datetime:
            accept:
            accept-language:
            accept-encoding:
            Content-Type:
            x-device:
            x-application:
            x-channel:
            user-agent:
        body:
            application/json:
                example:    |
                    {
                        "rqBody":{
                            "product_code": "AN012",
                            "product_description": "Andy Test Product",
                            "product_group": "TES",
                            "currency": "IDR",
                            "maximum_balance": 0,
                            "maximum_credit_per_month": 0,
                            "allow_negative_balance": "N",
                            "ownership_limit_per_cif": 1,
                            "ownership": 1,
                            "interest_id":"",
                            "interest_posting":1,
                            "interest_posting_frequency":"D"
                        }
                    }
        responses: 
            200:
                body: 
                    application/json:
                        example:  |
                            {
                                "rsBody": {
                                    "product_code": "AN012",
                                    "product_description": "Andy Test Product"
                                },
                                "error": []
                            }